name: Survenyer
packages:
  CSV:
    url: https://github.com/yaslab/CSV.swift
    version: 2.4.2

options:
  deploymentTarget:
    iOS: 13.0
  bundleIdPrefix: com.saitoh0526.k

targets:
  Survenyer:
    platform: iOS
    type: application
    sources:
      - Survenyer
    settings:
      DEVELOPMENT_TEAM: 39WWX2FY3V
      INFOPLIST_FILE: Survenyer/Info.plist
    scheme:
      testTargets:
        - SurvenyerTests
    dependencies:
      - package: CSV

  SurvenyerTests:
    platform: iOS
    type: bundle.unit-test
    sources: SurvenyerTests
    dependencies:
      - target: Survenyer
  
  SurvenyerPreview:
    platform: iOS
    type: application
    deploymentTarget: "13.0"
    sources:
      - Survenyer
      - SurvenyerPreview
    settings:
      DEVELOPMENT_TEAM: 39WWX2FY3V
      INFOPLIST_FILE: Survenyer/Info.plist
    scheme:
      testTargets:
        - SurvenyerTests
    dependencies:
      - package: CSV
